### ISSUE TITLE
Allow overriding GOPROXY

### ISSUE THREAD

**Issue by broom9** [cdklabs/cdk-ecr-deployment#183]
```GOPROXY=https://goproxy.cn,https://goproxy.io,direct```

This line in Dockerfile is forcing us to use `goproxy.cn`, and it sometimes returns 504 Gateway Timeout and breaks our build. Can we make this configurable or overridable from an env var? Thanks.

```# get [https://goproxy.cn/sumdb/sum.golang.org/tile/8/0/062:](https://goproxy.cn/sumdb/sum.golang.org/tile/8/0/062) 200 OK (31.502s)
go: [gopkg.in/fsnotify.v1@v1.4.7:](http://gopkg.in/fsnotify.v1@v1.4.7) reading [https://goproxy.cn/gopkg.in/fsnotify.v1/@v/v1.4.7.mod:](https://goproxy.cn/gopkg.in/fsnotify.v1/@v/v1.4.7.mod) 504 Gateway Timeout
The command '/bin/sh -c go mod download -x' returned a non-zero code: 1```

**Comment by wchaws** [comment]
@broom9 According to `GOPROXY` [doc](https://go.dev/ref/mod#goproxy-protocol), it will fallback to the next proxy if go  command encountered an error. However, the behavior between comma split(,) and pipe split(|) list is different. I think we should change from comma split to pipe split, because it looks more robust. Again, I don't against to let user to override `GOPROXY` env. But since cdk-ecr-deployment already pre-built golang binary, I don't understand why we still need to built from scratch?

> The go command may be configured to contact proxies or source control servers using the GOPROXY environment variable, which accepts a list of proxy URLs. The list may include the keywords direct or off (see [Environment variables](https://go.dev/ref/mod#environment-variables) for details). **List elements may be separated by commas (,) or pipes (|), which determine error fallback behavior. When a URL is followed by a comma, the go command falls back to later sources only after a 404 (Not Found) or 410 (Gone) response. When a URL is followed by a pipe, the go command falls back to later sources after any error, including non-HTTP errors such as timeouts.**

**Comment by broom9** [comment]
Thanks. I agree pipe looks more robust.

The code logic is to rebuild the image from scratch if on CI (when the `CI` env var is set to 1). So this issue happened in our CI pipelines.

**Comment by marcin-kwasnicki** [comment]
@wchaws Hi, can your change with the GOPROXY separator be also added to v1?
